[2023-11-21T00:38:39.499+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T00:38:39.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T00:38:39.523+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:38:39.555+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_data> on 2023-11-11 00:00:00+00:00
[2023-11-21T00:38:39.585+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2023-11-21T00:38:39.602+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'transform_data', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp3kck3jxp']
[2023-11-21T00:38:39.619+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask transform_data
[2023-11-21T00:38:39.946+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.transform_data scheduled__2023-11-11T00:00:00+00:00 [running]> on host c6d84631e1b9
[2023-11-21T00:38:40.182+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-21T00:38:41.424+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 118, in transform_data
    obj = s3.get_object(Bucket=bucket_name, Key=s3_object_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
[2023-11-21T00:38:41.472+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=shelter_data_dag, task_id=transform_data, execution_date=20231111T000000, start_date=20231121T003839, end_date=20231121T003841
[2023-11-21T00:38:41.539+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 109 for task transform_data (An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.; 63)
[2023-11-21T00:38:41.581+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T00:38:41.683+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-21T00:49:21.468+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T00:49:21.480+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shelter_data_dag.transform_data scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-21T00:49:21.481+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T00:49:21.493+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_data> on 2023-11-11 00:00:00+00:00
[2023-11-21T00:49:21.506+0000] {standard_task_runner.py:57} INFO - Started process 279 to run task
[2023-11-21T00:49:21.533+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'shelter_data_dag', 'transform_data', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpcr2noru9']
[2023-11-21T00:49:21.541+0000] {standard_task_runner.py:85} INFO - Job 177: Subtask transform_data
[2023-11-21T00:49:21.667+0000] {task_command.py:416} INFO - Running <TaskInstance: shelter_data_dag.transform_data scheduled__2023-11-11T00:00:00+00:00 [running]> on host 51d09cf321f5
[2023-11-21T00:49:21.766+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shelter_data_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-21T00:49:23.571+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-21T00:49:23.640+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=shelter_data_dag, task_id=transform_data, execution_date=20231111T000000, start_date=20231121T004921, end_date=20231121T004923
[2023-11-21T00:49:23.766+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-21T00:49:23.854+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
